image: nikolaik/python-nodejs:latest

variables:
  POSTGRES_DB: dusken
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"

cache:
  paths:
    - "$CI_PROJECT_DIR/pip-cache"
    - "$CI_PROJECT_DIR/dusken/static/node_modules"
    - "$CI_PROJECT_DIR/dusken/static/bower_components"
  key: "$CI_PROJECT_ID"

before_script:
  - apt update && apt install libsasl2-dev libldap2-dev -y
  - python -V
  - node -v
  - npm install -g bower gulp-cli
  - cd dusken/static; yarn && bower --allow-root install && gulp; cd ../..
  - pip install -r requirements.txt
  - pip install coverage

test:
  script:
    - python manage.py migrate
    - coverage run --source='./dusken/' manage.py test
    - coverage report
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
