image: nikolaik/python-nodejs:latest

services:
  - redis:latest

variables:
  POSTGRES_DB: dusken
  CELERY_BROKER_URL: "redis://redis:6379/0"
  PIPENV_VENV_IN_PROJECT: 1

cache:
  paths:
    - "$CI_PROJECT_DIR/.venv"
    - "$CI_PROJECT_DIR/dusken/static/node_modules"
  key: "$CI_PROJECT_ID"

before_script:
  - apt-get update && apt-get install libsasl2-dev libldap2-dev -y
  - python -V
  - node -v
  - cd dusken/static; yarn && yarn build; cd ../..
  - pipenv sync --dev

test:
  script:
    - pipenv run coverage run --source=dusken,apps --omit=dusken/migrations/*,apps/*/migrations/* manage.py test -v2
    - pipenv run coverage report
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
