image: nikolaik/python-nodejs:latest

variables:
  POSTGRES_DB: dusken
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"

cache:
  paths:
    - "$CI_PROJECT_DIR/pip-cache"
    - "$CI_PROJECT_DIR/dusken/static/node_modules"
  key: "$CI_PROJECT_ID"

before_script:
  - apt update && apt install libsasl2-dev libldap2-dev -y
  - python -V
  - node -v
  - npm install -g gulp-cli
  - cd dusken/static; yarn && gulp; cd ../..
  - pip install -r requirements.txt
  - pip install coverage

test:
  script:
    - coverage run --source=dusken,apps --omit=dusken/migrations/*,apps/*/migrations/* manage.py test -v2
    - coverage report
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
