version: 2
jobs:
  build:
    working_directory: ~/dusken
    docker:
      - image: circleci/python:3.6
      - image: redis:latest
        environment:
          PIPENV_VENV_IN_PROJECT: 1
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update; sudo apt-get install libsasl2-dev libldap2-dev -y
            pipenv sync --dev
      - save_cache:
          key: cache-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.venv
      - run:
          name: Run tests
          command: pipenv run coverage run --source=dusken,apps manage.py test -v 2
      - run:
          name: Upload coverage data
          command: pipenv run bash <(curl -s https://codecov.io/bash)
